//* Constants

pub const REGISTERED_MP4RA_BRANDS: &[BrandInfo] = &[
    //? https://www.ftyps.com cross referenced with https://mp4ra.org/registered-types/brands
    BrandInfo { brand: b"1pic", description: "Single intra-coded picture" },
    BrandInfo { brand: b"3g2a", description: "3GPP2" },
    BrandInfo { brand: b"3ge6", description: "3GPP Release 6 extended-presentation Profile" },
    BrandInfo { brand: b"3ge7", description: "3GPP Release 7 extended-presentation Profile" },
    BrandInfo { brand: b"3ge9", description: "3GPP Release 9 Extended Presentation Profile" },
    BrandInfo { brand: b"3gf9", description: "3GPP Release 9 File-delivery Server Profile" },
    BrandInfo { brand: b"3gg6", description: "3GPP Release 6 General Profile" },
    BrandInfo { brand: b"3gg9", description: "3GPP Release 9 General Profile" },
    BrandInfo { brand: b"3gh9", description: "3GPP Release 9 Adaptive Streaming Profile" },
    BrandInfo { brand: b"3gm9", description: "3GPP Release 9 Media Segment Profile" },
    BrandInfo { brand: b"3gmA", description: "3GPP Media Segment conforming to the Media Segment Format for 3GP DASH" },
    BrandInfo { brand: b"3gp4", description: "3GPP Release 4" },
    BrandInfo { brand: b"3gp5", description: "3GPP Release 5" },
    BrandInfo { brand: b"3gp6", description: "3GPP Release 6 basic Profile" },
    BrandInfo { brand: b"3gp7", description: "3GPP Release 7" },
    BrandInfo { brand: b"3gp8", description: "3GPP Release 8" },
    BrandInfo { brand: b"3gp9", description: "3GPP Release 9 Basic Profile" },
    BrandInfo { brand: b"3gr6", description: "3GPP Release 6 progressive-download Profile" },
    BrandInfo { brand: b"3gr9", description: "3GPP Release 9 Progressive DownloadProfile" },
    BrandInfo { brand: b"3gs6", description: "3GPP Release 6 streaming-server Profile" },
    BrandInfo { brand: b"3gs9", description: "3GPP Release 9 Streaming ServerProfile" },
    BrandInfo { brand: b"3gt8", description: "3GPP Release 8 Media Stream Recording Profile" },
    BrandInfo { brand: b"3gt9", description: "3GPP Release 9 Media Stream Recording Profile" },
    BrandInfo { brand: b"3gtv", description: "3GPP TV over 3GPP services" },
    BrandInfo { brand: b"3gvr", description: "3GPP VR Presentation" },
    BrandInfo { brand: b"3vra", description: "3GPP VR Advanced Video Media Profile" },
    BrandInfo { brand: b"3vrb", description: "3GPP VR Basic Video Media Profile" },
    BrandInfo { brand: b"3vrm", description: "3GPP VR Main Video Media Profile" },
    BrandInfo { brand: b"adti", description: "Advanced tiling OMAF video profile" },
    BrandInfo { brand: b"aid3", description: "ID3 metadata carried as timed metadata in CMAF" },
    BrandInfo { brand: b"ARRI", description: "ARRI Digital Camera" },
    BrandInfo { brand: b"av01", description: "AOM Video Codec" },
    BrandInfo { brand: b"avc1", description: "Advanced Video Coding extensions" },
    BrandInfo { brand: b"avci", description: "AVC image and image collection brands" },
    BrandInfo { brand: b"avcs", description: "AVC image sequence brands" },
    BrandInfo { brand: b"avde", description: "AVC-based viewport-dependent OMAF video profile" },
    BrandInfo { brand: b"avif", description: "AV1 image format brand" },
    BrandInfo { brand: b"avio", description: "AV1 intra-only brand" },
    BrandInfo { brand: b"avis", description: "AV1 image sequence brand" },
    BrandInfo { brand: b"bbxm", description: "Blinkbox Master File: H.264 video and 16-bit little-endian LPCM audio" },
    BrandInfo { brand: b"ca3a", description: "CMAF Media Profile – AVS3-P3" },
    BrandInfo { brand: b"ca4e", description: "CMAF Media Profile - AC-4 subsample encrypted" },
    BrandInfo { brand: b"ca4m", description: "CMAF Media Profile - AC-4 Main" },
    BrandInfo { brand: b"ca4s", description: "CMAF Media Profile - AC-4 Single Stream" },
    BrandInfo { brand: b"caaa", description: "CMAF Media Profile - AAC Adaptive Audio" },
    BrandInfo { brand: b"caac", description: "CMAF Media Profile - AAC Core" },
    BrandInfo { brand: b"cabl", description: "CMAF Media Profile for OMAF 3D audio baseline profile" },
    BrandInfo { brand: b"CAEP", description: "Canon Digital Camera" },
    BrandInfo { brand: b"cafr", description: "CMAF Media Profile for ATSC Full Range Constrained Baseline VVC" },
    BrandInfo { brand: b"cama", description: "CMAF Media Profile - AAC multichannel adaptive audio" },
    BrandInfo { brand: b"camc", description: "CMAF Media Profile - AAC multichannel audio" },
    BrandInfo { brand: b"caqv", description: "Casio Digital Camera" },
    BrandInfo { brand: b"casu", description: "CMAF Media Profile - MPEG-D USAC audio" },
    BrandInfo { brand: b"ccea", description: "CMAF Supplemental Data - CEA-608/708" },
    BrandInfo { brand: b"ccff", description: "Common container file format" },
    BrandInfo { brand: b"CDes", description: "Convergent Designs" },
    BrandInfo { brand: b"cdm1", description: "CMAF Media Profile - HEVC HDR10 (chd1) with SCTE Dynamic Metadata app #1 (ST2094-10)" },
    BrandInfo { brand: b"cdm4", description: "CMAF Media Profile compatibility to HDR10+ (ST2094-40)" },
    BrandInfo { brand: b"ceac", description: "CMAF Media Profile - Enhanced AC-3" },
    BrandInfo { brand: b"cevb", description: "CMAF EVC Baseline Media Profile" },
    BrandInfo { brand: b"cevm", description: "CMAF EVC Main Media Profile" },
    BrandInfo { brand: b"cfhd", description: "CMAF Media Profile - AVC HD" },
    BrandInfo { brand: b"cfsd", description: "CMAF Media Profile - AVC SD" },
    BrandInfo { brand: b"chd1", description: "CMAF Media Profile - HEVC HDR10" },
    BrandInfo { brand: b"chd2", description: "CMAF High frame rate Media Profile - HEVC HDR10H" },
    BrandInfo { brand: b"chdf", description: "CMAF Media Profile - AVC HDHF" },
    BrandInfo { brand: b"chev", description: "CMAF Media Profile for the HEVC-based viewport-dependent OMAF video profile" },
    BrandInfo { brand: b"chh1", description: "CMAF Media Profile - HEVC HHD10" },
    BrandInfo { brand: b"chhd", description: "CMAF Media Profile - HEVC HHD8" },
    BrandInfo { brand: b"cint", description: "CMAF Interlaced Media Profile - INT10" },
    BrandInfo { brand: b"clg1", description: "CMAF Media Profile - HEVC HLG10" },
    BrandInfo { brand: b"clg2", description: "CMAF High frame rate Media Profile - HEVC HLG10H" },
    BrandInfo { brand: b"clv1", description: "CMAF Media Profile for MPEG-5 LCEVC" },
    BrandInfo { brand: b"cmf2", description: "CMAF Structural Brand" },
    BrandInfo { brand: b"cmfc", description: "CMAF Structural Brand" },
    BrandInfo { brand: b"cmff", description: "CMAF Fragment Format" },
    BrandInfo { brand: b"cmfl", description: "CMAF Chunk Format" },
    BrandInfo { brand: b"cmfr", description: "CMAF Random Access chunk" },
    BrandInfo { brand: b"cmfs", description: "CMAF Segment Format" },
    BrandInfo { brand: b"cmh1", description: "MPEG-H audio BL single-stream media profile" },
    BrandInfo { brand: b"cmh2", description: "MPEG-H audio BL multi-stream media profile" },
    BrandInfo { brand: b"cmhm", description: "CMAF Media Profile - MPEG-H 3D audio LC (mhm2)" },
    BrandInfo { brand: b"cmhs", description: "CMAF Media Profile - MPEG-H 3D audio LC (mhm1)" },
    BrandInfo { brand: b"comp", description: "Compressed boxes" },
    BrandInfo { brand: b"csh1", description: "CMAF Media Profile - Scalable HEVC media profile" },
    BrandInfo { brand: b"cud1", description: "CMAF Media Profile - HEVC UHD10" },
    BrandInfo { brand: b"cud2", description: "CMAF High frame rate Media Profile - HEVC UHD10H" },
    BrandInfo { brand: b"cud8", description: "CMAF Media Profile - HEVC UHD8" },
    BrandInfo { brand: b"cud9", description: "CMAF High frame rate Media Profile - HEVC UHD8H" },
    BrandInfo { brand: b"cuvd", description: "CMAF Media Profile for the unconstrained HEVC-based viewport-independent OMAF video profile" },
    BrandInfo { brand: b"cvid", description: "CMAF Media Profile for the HEVC-based viewport-independent OMAF video profile" },
    BrandInfo { brand: b"cvvc", description: "Baseline VVC media profile" },
    BrandInfo { brand: b"cvvm", description: "CMAF Media Profile for Constrained Multilayer VVC" },
    BrandInfo { brand: b"cwvt", description: "CMAF Media Profile - WebVTT" },
    BrandInfo { brand: b"da0a", description: "DMB AF audio with MPEG Layer II audio, MOT slide show, DLS, JPG/PNG/MNG images" },
    BrandInfo { brand: b"da0b", description: "DMB AF, extending da0a , with 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"da1a", description: "DMB AF audio with ER-BSAC audio, JPG/PNG/MNG images" },
    BrandInfo { brand: b"da1b", description: "DMB AF, extending da1a, with 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"da2a", description: "DMB AF audio with HE-AAC v2 audio, MOT slide show, DLS, JPG/PNG/MNG images" },
    BrandInfo { brand: b"da2b", description: "DMB AF extending da2a, with 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"da3a", description: "DMB AF audio with HE-AAC, JPG/PNG/MNG images" },
    BrandInfo { brand: b"da3b", description: "DMB AF extending da3a with BIFS, 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"dash", description: "ISO base media file format file specifically designed for DASH including movie fragments and Segment Index." },
    BrandInfo { brand: b"db1p", description: "Dolby Vision cross-compatible with HDR10" },
    BrandInfo { brand: b"db2g", description: "Dolby Vision cross-compatible with SDR" },
    BrandInfo { brand: b"db4g", description: "Dolby Vision cross-compatible with HLG (VUI=14)" },
    BrandInfo { brand: b"db4h", description: "Dolby Vision cross-compatible with HLG (VUI =18)" },
    BrandInfo { brand: b"dby1", description: "MP4 files with Dolby content (e.g. Dolby AC-4, Dolby Digital Plus, Dolby TrueHD (Dolby MLP))" },
    BrandInfo { brand: b"dmb1", description: "DMB AF supporting all the components defined in the specification" },
    BrandInfo { brand: b"dsms", description: "Media Segment conforming to the DASH Self-Initializing Media Segment format type for ISO base media file format" },
    BrandInfo { brand: b"dts1", description: "CMAF media profile for audio codecs dtsc dtsh or dtse" },
    BrandInfo { brand: b"dts2", description: "CMAF media profile for audio codec dtsx" },
    BrandInfo { brand: b"dts3", description: "CMAF media profile for audio codec dtsy" },
    BrandInfo { brand: b"dv09", description: "Dolby Vision Profile 9 CMAF Media Profile" },
    BrandInfo { brand: b"dv10", description: "Dolby Vision Profile 10 CMAF Media Profile" },
    BrandInfo { brand: b"dv1a", description: "DMB AF video with AVC video, ER-BSAC audio, BIFS, JPG/PNG/MNG images, TS" },
    BrandInfo { brand: b"dv1b", description: "DMB AF, extending dv1a, with 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"dv20", description: "Dolby Vision Profile 20 CMAF Media Profile" },
    BrandInfo { brand: b"dv2a", description: "DMB AF video with AVC video, HE-AACv2 audio, BIFS, JPG/PNG/MNG images, TS" },
    BrandInfo { brand: b"dv2b", description: "DMB AF extending dv2a, with 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"dv3a", description: "DMB AF video with AVC video, HE-AAC audio, BIFS, JPG/PNG/MNG images, TS" },
    BrandInfo { brand: b"dv3b", description: "DMB AF extending dv3a with 3GPP timed text, DID, TVA, REL, IPMP" },
    BrandInfo { brand: b"dv58", description: "Dolby Vision Profile 5/8 CMAF Media Profile" },
    BrandInfo { brand: b"dvr1", description: "DVB RTP" },
    BrandInfo { brand: b"dvt1", description: "DVB Transport Stream" },
    BrandInfo { brand: b"dxo ", description: "DxO ONE camera" },
    BrandInfo { brand: b"emsg", description: "Event message box present" },
    BrandInfo { brand: b"evbi", description: "EVC Baseline coded image" },
    BrandInfo { brand: b"evbs", description: "EVC Baseline coded image sequence" },
    BrandInfo { brand: b"evmi", description: "EVC Main coded image" },
    BrandInfo { brand: b"evms", description: "EVC Main coded image sequenc" },
    BrandInfo { brand: b"geo1", description: "The file is conformant to version 1 of NGA.STND.0076-01_V1.0_GIMI" },
    BrandInfo { brand: b"gltf", description: "glTF JSON document as primary metadata item with timed media" },
    BrandInfo { brand: b"heic", description: "HEVC image and image collection brands" },
    BrandInfo { brand: b"heim", description: "L-HEVC image and image collection brands" },
    BrandInfo { brand: b"heis", description: "L-HEVC image and image collection brands" },
    BrandInfo { brand: b"heix", description: "HEVC image and image collection brands" },
    BrandInfo { brand: b"heoi", description: "OMAF HEVC image profile" },
    BrandInfo { brand: b"hevc", description: "HEVC image sequence brands" },
    BrandInfo { brand: b"hevd", description: "HEVC-based viewport-dependent OMAF video profile" },
    BrandInfo { brand: b"hevi", description: "HEVC-based viewport-independent OMAF video profile" },
    BrandInfo { brand: b"hevm", description: "L-HEVC image sequence brands" },
    BrandInfo { brand: b"hevs", description: "L-HEVC image sequence brands" },
    BrandInfo { brand: b"hevx", description: "HEVC image sequence brands" },
    BrandInfo { brand: b"hvce", description: "L-HEVC explicit reconstruction" },
    BrandInfo { brand: b"hvci", description: "L-HEVC implicit reconstruction" },
    BrandInfo { brand: b"hvcx", description: "L-HEVC extended explicit reconstruction brand" },
    BrandInfo { brand: b"hvti", description: "HEVC Tile Track" },
    BrandInfo { brand: b"iamf", description: "Immersive Audio Model and Formats - Encapsulated IA Sequence" },
    BrandInfo { brand: b"ifaa", description: "The IFE-AAC Core Media Profile" },
    BrandInfo { brand: b"ifah", description: "The IFE-AV1-HD Media Profile" },
    BrandInfo { brand: b"ifai", description: "The IFE-AV1-HDHDR Media Profile" },
    BrandInfo { brand: b"ifas", description: "The IFE-AV1-SD Media Profile" },
    BrandInfo { brand: b"ifau", description: "The IFE-AV1-UHD10 Media Profile" },
    BrandInfo { brand: b"ifav", description: "The IFE-AV1-HDR10 Media Profile" },
    BrandInfo { brand: b"ifhd", description: "The IFE-HD Media Profile" },
    BrandInfo { brand: b"ifhh", description: "The IFE-HDHDR Media Profile" },
    BrandInfo { brand: b"ifhr", description: "The IFE-HDR10 Media Profile" },
    BrandInfo { brand: b"ifhs", description: "The IFE-HSD Media Profile" },
    BrandInfo { brand: b"ifhu", description: "The IFE-UHD10 Media Profile" },
    BrandInfo { brand: b"ifhx", description: "The IFE-HHD10 Media Profile" },
    BrandInfo { brand: b"ifrm", description: "Apple iFrame Specification, Version 8.1 Jan 2013" },
    BrandInfo { brand: b"ifsd", description: "The IFE-SD Media Profile" },
    BrandInfo { brand: b"im1i", description: "CMAF Media Profile - IMSC1 Image" },
    BrandInfo { brand: b"im1t", description: "CMAF Media Profile - IMSC1 Text" },
    BrandInfo { brand: b"im2i", description: "CMAF Media Profile - IMSC1.1 Image" },
    BrandInfo { brand: b"im2t", description: "CMAF Media Profile - IMSC1.1 Text" },
    BrandInfo { brand: b"isc2", description: "Files encrypted according to ISMACryp 2.0" },
    BrandInfo { brand: b"iso2", description: "All files based on the 2004 edition of the ISO file format" },
    BrandInfo { brand: b"iso3", description: "Version of the ISO file format" },
    BrandInfo { brand: b"iso4", description: "Version of the ISO file format" },
    BrandInfo { brand: b"iso5", description: "Version of the ISO file format" },
    BrandInfo { brand: b"iso6", description: "Version of the ISO file format" },
    BrandInfo { brand: b"iso7", description: "Version of the ISO file format" },
    BrandInfo { brand: b"iso8", description: "Version of the ISO file format" },
    BrandInfo { brand: b"iso9", description: "Version of the ISO file format" },
    BrandInfo { brand: b"isoa", description: "Version of the ISO file format" },
    BrandInfo { brand: b"isob", description: "Version of the ISO file format" },
    BrandInfo { brand: b"isoc", description: "Version of the ISO file format" },
    BrandInfo { brand: b"isod", description: "Version of the ISO file format" },
    BrandInfo { brand: b"isom", description: "All files based on the ISO Base Media File Format" },
    BrandInfo { brand: b"j2is", description: "JPEG 2000 image sequence in ISO/IEC 23008-12 files" },
    BrandInfo { brand: b"j2ki", description: "JPEG 2000 image and image collections in ISO/IEC 23008-12 files" },
    BrandInfo { brand: b"j2ks", description: "Motion JPEG 2000 in ISO/IEC 23008-12 files" },
    BrandInfo { brand: b"J2P0", description: "JPEG2000 Profile 0" },
    BrandInfo { brand: b"J2P1", description: "JPEG2000 Profile 1" },
    BrandInfo { brand: b"jaii", description: "JPEG AI coded image" },
    BrandInfo { brand: b"jp2 ", description: "JPEG2000 Part 1" },
    BrandInfo { brand: b"jpeg", description: "JPEG-specific still image brand" },
    BrandInfo { brand: b"jpgs", description: "JPEG image sequence brands" },
    BrandInfo { brand: b"jpm ", description: "JPEG 2000 Part 6 Compound Images" },
    BrandInfo { brand: b"jpoi", description: "OMAF legacy image profile" },
    BrandInfo { brand: b"jpsi", description: "The JPSearch data interchange format, for the exchange of image collections and respective metadata" },
    BrandInfo { brand: b"jpx ", description: "JPEG2000 Part 2" },
    BrandInfo { brand: b"jpxb", description: "JPEG XR" },
    BrandInfo { brand: b"jxl ", description: "JPEG XL" },
    BrandInfo { brand: b"jxs ", description: "Still Image File Format for JPEG XS" },
    BrandInfo { brand: b"jxsc", description: "Codestream for JPEG XS" },
    BrandInfo { brand: b"jxsi", description: "JPEG XS image and image collections for HEIF" },
    BrandInfo { brand: b"jxss", description: "JPEG XS image sequences for HEIF" },
    BrandInfo { brand: b"LCAG", description: "Leica digital camera" },
    BrandInfo { brand: b"lhte", description: "L-HEVC Tile Track Explicit brand" },
    BrandInfo { brand: b"lhti", description: "L-HEVC Tile Track Implicit brand" },
    BrandInfo { brand: b"lmsg", description: "last Media Segment indicator for ISO base media file format." },
    BrandInfo { brand: b"M4A ", description: "iTunes MPEG-4 audio protected or not, can contain audio + video + 3g text track + chapter track" },
    BrandInfo { brand: b"M4B ", description: "iTunes AudioBook protected or not, can contain audio + video + 3g text track + chapter track" },
    BrandInfo { brand: b"M4P ", description: "MPEG-4 protected audio" },
    BrandInfo { brand: b"M4V ", description: "MPEG-4 protected audio+video" },
    BrandInfo { brand: b"MA1A", description: "AVIF Advanced Profile" },
    BrandInfo { brand: b"MA1B", description: "AVIF Baseline Profile" },
    BrandInfo { brand: b"MFSM", description: "Media File for Samsung video Metadata" },
    BrandInfo { brand: b"MGSV", description: "Home and Mobile Multimedia Platform (HMMP)" },
    BrandInfo { brand: b"MiAB", description: "Multi-Image Application format brand for MIAF AVC Basic Profile" },
    BrandInfo { brand: b"MiAC", description: "Multi-Image Application format brand for fragmented alpha video" },
    BrandInfo { brand: b"miaf", description: "Multi-Image Application format brand for general MIAF requirements" },
    BrandInfo { brand: b"MiAn", description: "Mutli-Image Application format brand for animation" },
    BrandInfo { brand: b"MiBu", description: "Multi-Image Application format brand for burst capture" },
    BrandInfo { brand: b"MiCm", description: "Multi-Image Application format brand for CMAF compatibility" },
    BrandInfo { brand: b"mif1", description: "Image file format structural brand" },
    BrandInfo { brand: b"mif2", description: "Image file format structural brand CICP alpha and depth" },
    BrandInfo { brand: b"MiHA", description: "Multi-Image Application format brand for MIAF HEVC Advanced Profile" },
    BrandInfo { brand: b"MiHB", description: "Multi-Image Application format brand for MIAF HEVC Basic Profile" },
    BrandInfo { brand: b"MiHE", description: "Multi-Image Application format brand for MIAF HEVC Extended Profile" },
    BrandInfo { brand: b"MiPr", description: "Multi-Image Application format brand for progressive decoding and rendering" },
    BrandInfo { brand: b"mj2s", description: "Motion JPEG 2000 simple profile" },
    BrandInfo { brand: b"mjp2", description: "Motion JPEG 2000, general profile" },
    BrandInfo { brand: b"mp21", description: "MPEG-21" },
    BrandInfo { brand: b"mp41", description: "MP4 version 1" },
    BrandInfo { brand: b"mp42", description: "MP4 version 2" },
    BrandInfo { brand: b"mp71", description: "MPEG-7 file-level metadata" },
    BrandInfo { brand: b"MPPI", description: "Photo Player Multimedia Application Format" },
    BrandInfo { brand: b"mpuf", description: "Compliance with the MMT Processing Unit format" },
    BrandInfo { brand: b"msdh", description: "Media Segment conforming to the general format type for ISO base media file format." },
    BrandInfo { brand: b"msf1", description: "Image file format structural brand" },
    BrandInfo { brand: b"msix", description: "Media Segment conforming to the Indexed Media Segment format type for ISO base media file format." },
    BrandInfo { brand: b"MSNV", description: "Portable multimedia CE products using MP4 file format with AVC video codec and AAC audio codec" },
    BrandInfo { brand: b"muxa", description: "Apple HEVC Video with Alpha" },
    BrandInfo { brand: b"niko", description: "Nikon Digital Camera" },
    BrandInfo { brand: b"nlsl", description: "Non-linear storyline toolset brand" },
    BrandInfo { brand: b"nras", description: "No Leading Picture Sync Brand" },
    BrandInfo { brand: b"oa2d", description: "OMAF 2D audio legacy profile" },
    BrandInfo { brand: b"oabl", description: "OMAF 3D audio baseline profile" },
    BrandInfo { brand: b"odcf", description: "OMA DCF (DRM Content Format)" },
    BrandInfo { brand: b"ompp", description: "OMAF viewport-independent baseline presentation profile" },
    BrandInfo { brand: b"opf2", description: "OMA PDCF (DRM Content Format)" },
    BrandInfo { brand: b"opx2", description: "OMA Adapted PDCF" },
    BrandInfo { brand: b"ovdp", description: "OMAF viewport-dependent baseline presentation profile" },
    BrandInfo { brand: b"ovly", description: "Overlay toolset brand" },
    BrandInfo { brand: b"paff", description: "Generic Partial File" },
    BrandInfo { brand: b"pana", description: "Panasonic Digital Camera" },
    BrandInfo { brand: b"piff", description: "Protected Interoperable File Format" },
    BrandInfo { brand: b"pmff", description: "Mixed Partial File" },
    BrandInfo { brand: b"pnvi", description: "Panasonic Video Intercom" },
    BrandInfo { brand: b"pred", description: "Image file format brand for predictively coded image items" },
    BrandInfo { brand: b"qt  ", description: "QuickTime" },
    BrandInfo { brand: b"relo", description: "combination brand to indicate relative addressing" },
    BrandInfo { brand: b"risx", description: "Representation Index Segment used to index MPEG-2 TS based Media Segments." },
    BrandInfo { brand: b"ROSS", description: "Ross Video" },
    BrandInfo { brand: b"saie", description: "SampleAuxiliaryInformationSizesBox with version 1 and 2" },
    BrandInfo { brand: b"SAV1", description: "ISOBMFF brand for Static Audible Verified X profile" },
    BrandInfo { brand: b"sdv ", description: "SD Video" },
    BrandInfo { brand: b"SEAU", description: "Home and Mobile Multimedia Platform (HMMP)" },
    BrandInfo { brand: b"SEBK", description: "Home and Mobile Multimedia Platform (HMMP)" },
    BrandInfo { brand: b"senv", description: "Video contents Sony Entertainment Network provides by using MP4 file format" },
    BrandInfo { brand: b"sims", description: "Media Segment conforming to the Sub-Indexed Media Segment format type for ISO base media file format." },
    BrandInfo { brand: b"sisx", description: "Single Index Segment used to index MPEG-2 TS based Media Segments." },
    BrandInfo { brand: b"siti", description: "HEVC-based simple tiling OMAF video profile" },
    BrandInfo { brand: b"sitv", description: "VVC-based simple tiling OMAF video profile" },
    BrandInfo { brand: b"slh1", description: "Dynamic metadata for Single Layer SDR-compatible HDR video streams" },
    BrandInfo { brand: b"slh2", description: "Dynamic metadata for Single Layer PQ-based HDR video streams" },
    BrandInfo { brand: b"slh3", description: "Dynamic metadata for Single Layer HLG-based HDR video streams" },
    BrandInfo { brand: b"sm01", description: "The file carries GIMI Security XML markings" },
    BrandInfo { brand: b"ssss", description: "Subsegment Index Segment used to index MPEG-2 TS based Media Segments." },
    BrandInfo { brand: b"tmap", description: "Tone-map derived image item present" },
    BrandInfo { brand: b"ttml", description: "OMAF IMSC1 timed text profile" },
    BrandInfo { brand: b"ttwv", description: "OMAF WebVTT timed text profile" },
    BrandInfo { brand: b"uhvi", description: "Unconstrained HEVC-based viewport-independent OMAF video profile" },
    BrandInfo { brand: b"unif", description: "Unified identifiers" },
    BrandInfo { brand: b"uvvu", description: "UltraViolet file brand – conforming to the DECE Common File Format spec, Annex E." },
    BrandInfo { brand: b"v3mp", description: "Multi-track encapsulation mode for V3C data with partial access support" },
    BrandInfo { brand: b"v3mt", description: "Multi-track encapsulation mode for V3C data" },
    BrandInfo { brand: b"v3nt", description: "Non-timed encpasulation mode for V3C data" },
    BrandInfo { brand: b"v3st", description: "Single-track encapsulation mode for V3C data" },
    BrandInfo { brand: b"vvci", description: "VVC-based viewport-independent OMAF video profile" },
    BrandInfo { brand: b"vvic", description: "VVC coded image item" },
    BrandInfo { brand: b"vvis", description: "VVC coded image sequence" },
    BrandInfo { brand: b"vvoi", description: "OMAF VVC image profile" },
    BrandInfo { brand: b"vwpt", description: "Viewpoint toolset brand" },
    BrandInfo { brand: b"XAVC", description: "XAVC File Format" },
    BrandInfo { brand: b"XFVC", description: "XF-AVC S/XF-HEVC S File Format" },
    BrandInfo { brand: b"yt4 ", description: "Google specification for use by YouTube apps" },
];

struct BrandInfo {
    brand: &'static [u8; 4],
    description: &'static str,
}
